# Generated by Django 5.1.4 on 2026-02-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbackend', '0006_item_combo_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comboitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
