# Generated by Django 5.1.4 on 2026-02-09 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbackend', '0008_riderotp_rider'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='foodbackend.rider'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready_for_pickup', 'Ready For Pickup'), ('pickup_pending', 'Pickup Pending'), ('on_the_way', 'On The Way'), ('delivery_pending', 'Delivery Pending'), ('pickup_failed', 'Pickup Failed'), ('pickup_rescheduled', 'Pickup Rescheduled'), ('delivery_failed', 'Delivery Failed'), ('delivery_rescheduled', 'Delivery Rescheduled'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
