# Generated by Django 5.1.4 on 2026-02-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbackend', '0009_order_rider_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_otp',
            field=models.CharField(default='1234', max_length=6),
        ),
    ]
