# Generated by Django 5.1.4 on 2026-02-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbackend', '0010_order_delivery_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rider_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rider_location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rider_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rider_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rider_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
