# Generated by Django 5.1.4 on 2026-02-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbackend', '0012_order_delivery_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_charge',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_otp',
            field=models.CharField(default='1234', max_length=6),
        ),
    ]
