# Generated by Django 5.1.4 on 2026-02-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbackend', '0013_remove_order_delivery_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
