# Generated by Django 4.2 on 2026-02-20 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodbackend', '0018_supportticket_fields'),
        ('foodbackend', '0019_supportticket_supportmessage'),
    ]

    operations = [
    ]
