# Generated by Django 4.2 on 2026-02-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbackend', '0020_merge_20260220_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='gst_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GST rate (%) for this item. Leave empty to use category GST.', max_digits=5, null=True),
        ),
    ]
