# Generated by Django 6.0.2 on 2026-02-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbackend', '0022_staffprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='force_password_change',
            field=models.BooleanField(default=True),
        ),
    ]
