# Generated by Django 6.0.2 on 2026-02-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbackend', '0023_staffprofile_force_password_change'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_available', 'is_combo'], name='foodbackend_is_avai_54d8c6_idx'),
        ),
    ]
