# Generated by Django 6.0.2 on 2026-02-26 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbackend', '0024_item_foodbackend_is_avai_54d8c6_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('media', models.ImageField(upload_to='home_banners/')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
