# Generated by Django 6.0.2 on 2026-02-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodbackend", "0025_homebanner"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="otp",
            index=models.Index(fields=["mobile", "created_at"], name="otp_mobile_created_idx"),
        ),
        migrations.AddIndex(
            model_name="riderotp",
            index=models.Index(fields=["mobile", "created_at"], name="riderotp_mobile_created_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["user", "created_at"], name="order_user_created_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["user", "status", "created_at"], name="order_user_status_created_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["rider", "created_at"], name="order_rider_created_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status", "rider", "created_at"], name="order_status_rider_created_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["rider_mobile"], name="order_rider_mobile_idx"),
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(
                fields=["is_active", "valid_from", "valid_until"],
                name="coupon_active_window_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(fields=["for_first_time_users_only"], name="coupon_first_time_idx"),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(fields=["user", "created_at"], name="supportticket_user_created_idx"),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(fields=["status", "created_at"], name="supticket_status_created_ix"),
        ),
        migrations.AddIndex(
            model_name="supportmessage",
            index=models.Index(fields=["ticket", "created_at"], name="supportmsg_ticket_created_idx"),
        ),
    ]
